### ISSUE TITLE
The scalability of elixir/phoenix in the future

### ISSUE THREAD

**Issue by Yuandong-Chen** [phoenixframework/phoenix_pubsub#104]
I've noticed that lasp/partisan enables erlang/elixir to scale up to 1k nodes, however, elixir/phoenix itself is totally built upon distributed erlang. Does phoenix.pubsub.redis mitigate this problem?  What if we somehow want to scale elixir/phoenix upto 1k nodes?

**Comment by josevalim** [comment]
@Yuandong-Chen You can replace the Phoenix.PubSub adapter by a custom implementation that uses Partisan instead of Distributed Erlang/Redis. That's exactly the goal of the adapters, to make the broadcast mechanism replaceable.
