### ISSUE TITLE
Message ordering

### ISSUE THREAD

**Issue by xinhaoyuan** [phoenixframework/phoenix_pubsub#117]
Should message ordering be preserved when a `broadcast` call returns before another `broadcast` call begins? I've done some testing and found some counterexamples -- not sure whether it's a bug or not.

**Comment by josevalim** [comment]
If I remember correctly, broadcast is sync, so as long as you are starting from the same process, it is not possible for you to start a broadcast call before another broadcast call. However, if you are talking about different processes, there is no ordering guarantees for broadcasts between different processes. So if process A broadcasts something, process B picks it up and broadcasts something else, there is a chance process C will see B's broadcast before A's.
