### ISSUE TITLE
Release v1.1.3 suppressing warnings

### ISSUE THREAD

**Issue by am-kantox** [phoenixframework/phoenix_pubsub#137]
This is a cosmetic one, but still.

7 months ago in [585a01](https://github.com/phoenixframework/phoenix_pubsub/commit/585a0155456f7220483f553f15d0863d8bc58eb2), the deprecated API (`Supervisor.Spec`) was removed. Could we have `v1.1.3`  released to hex.pm, please?

Thank you very much in advance!

**Comment by josevalim** [comment]
We will be shipping v2.0 soon which requires more recent Elixir versions and have those warnings addressed!
