### ISSUE TITLE
It may be helpful for users, if parallel option can be provided  when starting Registry. Without it partitions in registry executes sequentially.

### ISSUE THREAD

**Issue by sagarchamp007** [phoenixframework/phoenix_pubsub#141]
https://github.com/phoenixframework/phoenix_pubsub/blob/ca2b47c8cf31324b0bf96cea862058f783a3e7bd/lib/phoenix/pubsub/supervisor.ex#L26

**Comment by chrismccord** [comment]
There are other considerations when dispatching with`parallel` so without hard data on performance measurements you're seeing in the wild, it's best to leave as unless we have a reason to allow such an option. Thanks!
