### ISSUE TITLE
topic forced to be string

### ISSUE THREAD

**Issue by artemk** [phoenixframework/phoenix_pubsub#147]
Hi guys.
Any reason you [force](https://github.com/phoenixframework/phoenix_pubsub/blob/1bc0b25e888fc0ca80d190d3c2c0b68282aea257/lib/phoenix/tracker.ex#L111) topic to be string?

I have no problem using tuple instead of string, but dialyzer claims because it expect topic to be string. 

[phash2](https://erlang.org/doc/man/erlang.html#phash2-2), which is used inside, accepting term as a first argument. So any reason to force it to be string in lib?

**Comment by chrismccord** [comment]
Given different PubSub adapters and potential future features, such as wildcard broadcasts (not planned), it was locked down initially. A future pubsub release will likely open this up to support other terms, but not in the immediate future. Thanks!
