### ISSUE TITLE
Does Phoenix.PubSub itself support subscribing to wildcard topics?

### ISSUE THREAD

**Issue by Qqwy** [phoenixframework/phoenix_pubsub#152]
In the documentation of Phoenix.Channel we learn that they can subscribe to a whole group of topics by using an asterisk as special wildcard at the end of the topic specification.

In the documentation of Phoenix.PubSub there is no mention of this. I was also not immediately to find anything related to this in the codebase as a whole.

Is it supported for arbitrary processes to subscribe to wildcard topics or not?

**Comment by chrismccord** [comment]
The channel definition area about topic *routing*, not subscriptions. Wildcard subscription do not exist in channels or pubsub. Thanks!
