### ISSUE TITLE
[Feature Request] Be able to transform a module into a Pub.Sub

### ISSUE THREAD

**Issue by yordis** [phoenixframework/phoenix_pubsub#160]
Hey folk, I would like to do something like `Ecto.Repo`:

```elixir
defmodule MyRepo do
  use Ecto.Repo,
    otp_app: :hmbradley,
    adapter: Ecto.Adapters.Postgres
end
```

I would like to do 

```elixir
defmodule MyPubSub do
  use Phoenix.PubSub,
    adapter: Phoenix.PubSub.PG2
end
```

Then in my Supervisor,

```elixir
  def start(_type, _args) do
    children = [
      MyRepo,
      MyPubSub,
      # ....
    ]
  end
```

**Comment by Gazler** [comment]
Why would you like to do this? What benefit does it offer over the existing:

```
```

**Comment by yordis** [comment]
@Gazler maybe it is a matter of docs, so help me here.

From my perspective, I get to put static configuration and be able to override it the environment much easier, as well as be explicit in terms of the intention that such module and name is used for `Phoenix Pub.Sub`, and be able to change the adapter per pub/sub.

```elixir
defmodule MyPubSub do
  use Phoenix.PubSub,
    adapter: Phoenix.PubSub.PG2
end

defmodule AdminPubSub do
  use Phoenix.PubSub,
    adapter: Phoenix.PubSub.PG2
end
```

```elixir
# config/prod.exs

config MyPubSub,
      adapter: Phoenix.PubSub.Redis
```

---

@chrismccord would appreciate some feedback before closing it thou, people will get to learn about the decision made 🙏🏻

**Comment by chrismccord** [comment]
We don't accept feature requests on the issue tracker. The module and config in this case only serves as indirection so the supervision tree is preferred. Thanks!

**Comment by yordis** [comment]
> We don't accept feature requests on the issue tracker. 

Where do we suppose to send feature requests? It would help in the future to figure out what we suppose to do.

**Comment by arpunk** [comment]
> > We don't accept feature requests on the issue tracker.
> 
> Where do we suppose to send feature requests? It would help in the future to figure out what we suppose to do.

https://github.com/phoenixframework/phoenix/blob/master/CONTRIBUTING.md#feature-requests

**Comment by yordis** [comment]
@arpunk thank you so much, I will create a PR that helps to understand what to do when creating a new issue.
