### ISSUE TITLE
RFC: expose erlang pg's scope ability for Phoenix.PubSub.PG2 

### ISSUE THREAD

**Issue by xiaoqinglee** [phoenixframework/phoenix_pubsub#183]
> Process groups can be organised into multiple scopes. Scopes are completely independent of each other. A process may join any number of groups in any number of scopes. Scopes are designed to decouple single mesh into a set of overlay networks, reducing amount of traffic required to propagate group membership information. Default scope pg is started automatically when [kernel(6)](https://www.erlang.org/docs/27/apps/kernel/kernel_app#start_pg) is configured to do so.

[start_link/1](https://www.erlang.org/docs/27/apps/kernel/pg.html#start_link/1)

pg was contributed by Maxim Fedorov from WhatsApp. Maxim’s work is focused on performance and scalability of the server side.

[pg](https://erlangforums.com/t/did-the-whatsapp-patches-mentioned-in-a-2014-conference-make-it-into-mainstream-erlang/958/5)

[WhatsApp deprecated and removed wandist. With pg it is possible to create any number of disjoint sub-clusters (by running several pg scopes). ](https://erlangforums.com/t/anything-similar-to-wandist/1202/2)

**Comment by josevalim** [comment]
We don't plan to expose this in our default implementation but you can provide your own adapters to PubSub that relies on scope. Thank you!
