### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by lpil** [phoenixframework/phoenix_pubsub#32]

**Comment by chrismccord** [comment]
Please see the extensive moduledocs and generated hexdocs
https://github.com/phoenixframework/phoenix_pubsub/blob/master/lib/phoenix_pubsub/tracker.ex
Thanks!

**Comment by lpil** [comment]
I was expecting to find them here https://hexdocs.pm/phoenix_pubsub/

Is this not correct? Thanks :)

**Comment by chrismccord** [comment]
They will be pushed once we start ramping up for a release

**Comment by lpil** [comment]
Ah, great. I look forward to it.
