### ISSUE TITLE
Add small "hello world" example project

### ISSUE THREAD

**Issue by lpil** [phoenixframework/phoenix_pubsub#33]

**Comment by chrismccord** [comment]
Presence and PubSub have many usecases and application areas so a standalone hello world doesn't really fit. If you want an example usage with Phoenix.Presence, check out:

https://www.youtube.com/watch?v=9dALrnCOLNE

Other example repos are welcome, but probably won't be in the core lib. Thanks!

**Comment by lpil** [comment]
Makes sense. Thanks :)
