### ISSUE TITLE
Publish docs to hex?

### ISSUE THREAD

**Issue by antipax** [phoenixframework/phoenix_pubsub#42]
https://hex.pm/packages/phoenix_pubsub

Was looking for the Phoenix.PubSub.Tracker docs on hex and saw they weren't published.

**Comment by chrismccord** [comment]
https://hexdocs.pm/phoenix_pubsub/1.0.0-rc.0

Thanks for reminding me!

**Comment by antipax** [comment]
@chrismccord thanks!
