### ISSUE TITLE
Fastlanes via subscribe

### ISSUE THREAD

**Issue by merqlove** [phoenixframework/phoenix_pubsub#50]
Can't find way to make it works.

I.e.:
```elixir
Phoenix.PubSub.subscribe(:freeling, "freeling:#{id}", fastlane: {some_module_pid, SomeModule, ["some_id1"]})
```

Normal subscriber always called, but not fastlane destination.

Also tried to print subscribers, all right, it has fastlanes:
```
[{#PID<0.959.0>,
  {#PID<0.1006.0>, SomeModule,
   ["bdb59e6a-2a5d-11e6-be56-685b35999bd2"]}}]
[{#PID<0.959.0>,
  {#PID<0.1007.0>, SomeModule,
   ["bdb59e6a-2a5d-11e6-be56-685b35999bd2"]}}]
```

Seems that sending to local pid is forced.
[lib/phoenix/pubsub/local.ex#L115](https://github.com/phoenixframework/phoenix_pubsub/blob/master/lib/phoenix/pubsub/local.ex#L115)

```elixir
  defp do_broadcast(nil, pubsub_server, shard, from, topic, msg) do
    pubsub_server
    |> subscribers_with_fastlanes(topic, shard)
    |> Enum.each(fn
      {pid, _} when pid == from -> :noop
      {pid, _} -> send(pid, msg)
    end)
  end
```

**Comment by merqlove** [comment]
I'm asking this because in my case i can't send fastlane from broadcaster, but seems i can provide it at subscribe state..

**Comment by merqlove** [comment]
Example fastlane calback is:

```elixir
def fastlane(msg) do
  IO.inspect msg
  msg
end
```

**Comment by chrismccord** [comment]
Please verify the versions you are using, as well as the pubsub adapter. If using Redis please see if you can recreate with pg2. Failing that, a minimal example which recreates the issue would be very helpful. Thanks!

**Comment by merqlove** [comment]
Hello, Chris, thanks for fast reply.

```elixir
[{:phoenix_pubsub, "~> 1.0"},     
 {:phoenix_pubsub_redis, "~> 2.1.2"},]
```

In current project we have Mongo as primary source, so it can be a bit complicated :) 

Seems that this problem not depends on `Redis` or any other PubSub source at all, because they always call `Phoenix.PubSub.Local.broadcast/6 ` to deliver it for local subscribers.

**Comment by merqlove** [comment]
For example you did it in Redis PubSub:

```elixir
def handle_info({:redix_pubsub, redix_pid, :message, %{payload: bin_msg}}, %{redix_pid: redix_pid} = state) do
    {_vsn, remote_node_ref, fastlane, pool_size, from_pid, topic, msg} = :erlang.binary_to_term(bin_msg)
...
      Local.broadcast(fastlane, state.server_name, pool_size, from_pid, topic, msg)
...
    {:noreply, state}
end
```

So it's jus a call 👍 In my case fastlane argument will be nil, but subscribed pids can have fastlanes.

**Comment by merqlove** [comment]
Yeah, with PG2 the same issue.

**Comment by merqlove** [comment]
Did hotfix, now i will try to pull & test this repo. PG2 PubSub with/without fastlane works.

**Comment by merqlove** [comment]
Maybe something need to be in docs.
After this PR, i found that all works if i have setup of fastlane in PubSub init.

Seems it works like this:

```elixir
# lib/module_name.ex
supervisor(Phoenix.PubSub.Redis, [..., fastlane: ModuleName.Fastlane]]),
```

```elixir
# lib/module_name/fastlane.ex
defmodule ModuleName.Fastlane do
  def fastlane(subscribers, from, msg) do
    Enum.each(subscribers, fn
      {pid, _} when pid == from -> :noop
      {_, {fastlane_pid, module, data}} -> module.somemethod(fastlane_pid, msg, data)
      {pid, _} -> send(pid, msg)
    end)
  end
end
```
