### ISSUE TITLE
Zombie Pids from a restarted node may linger in the crdt.

### ISSUE THREAD

**Issue by gabiz** [phoenixframework/phoenix_pubsub#55]
When a replica is restarted then `permdown` is invoked in other nodes and the old instance removed from the `State`. However, it seems like not all the old instance info is cleaned up and sometimes the old instance resurfaces. Eventually, this old instance info finds its way back to the restarted replica and the zombie Pids are made available again. 

This is easier to reproduce with many nodes and low broadcast periods.

Here the `node4` out of 4 nodes is restarted and the old instance `{:"node4@127.0.0.1", 1473221321103120}` shows up along with invalid pids.

```bash
AudiaMBP:Dht gabiz$ iex --name node4@127.0.0.1 -S mix
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(node4@127.0.0.1)1>
21:08:45.127 [debug] node4@127.0.0.1: transfer_req from :"node1@127.0.0.1"

21:08:45.129 [debug] {:"node4@127.0.0.1", 1473221325050827}: sending delta generation 1

21:08:45.129 [debug] node4@127.0.0.1: transfer_req from :"node2@127.0.0.1"

21:08:45.129 [debug] {:"node4@127.0.0.1", 1473221325050827}: sending delta generation 1

21:08:45.141 [debug] node4@127.0.0.1: transfer_req from :"node3@127.0.0.1"

21:08:45.141 [debug] {:"node4@127.0.0.1", 1473221325050827}: sending delta generation 1

21:08:45.177 [debug] node4@127.0.0.1: replica up from :"node1@127.0.0.1"

21:08:45.177 [debug] node4@127.0.0.1: replica up from :"node2@127.0.0.1"

21:08:45.194 [debug] node4@127.0.0.1: replica up from :"node3@127.0.0.1"

21:08:45.210 [debug] node4@127.0.0.1: transfer_req from node3@127.0.0.1

21:08:45.212 [debug] node4@127.0.0.1: transfer_ack from :"node3@127.0.0.1"
iex(node4@127.0.0.1)1> GenServer.call(Dispatch.Registry, {:list, "dht"})
%Phoenix.Tracker.State{cloud: #MapSet<[]>,
 context: %{{:"node1@127.0.0.1", 1473221166666092} => 1,
   {:"node2@127.0.0.1", 1473221261730782} => 1,
   {:"node3@127.0.0.1", 1473221317066008} => 1,
   {:"node4@127.0.0.1", 1473221321103120} => 1,
   {:"node4@127.0.0.1", 1473221325050827} => 1},
 delta: %Phoenix.Tracker.State{cloud: #MapSet<[]>, context: %{}, delta: :unset,
  mode: :delta, pids: nil,
  range: {%{{:"node4@127.0.0.1", 1473221325050827} => 1},
   %{{:"node4@127.0.0.1", 1473221325050827} => 1}},
  replica: {:"node4@127.0.0.1", 1473221325050827}, replicas: %{}, values: %{}},
 mode: :normal, pids: 245817, range: {%{}, %{}},
 replica: {:"node4@127.0.0.1", 1473221325050827},
 replicas: %{{:"node1@127.0.0.1", 1473221166666092} => :up,
   {:"node2@127.0.0.1", 1473221261730782} => :up,
   {:"node3@127.0.0.1", 1473221317066008} => :up,
   {:"node4@127.0.0.1", 1473221325050827} => :up}, values: 241720}

iex(node4@127.0.0.1)3> Phoenix.Tracker.list(Dispatch.Registry, "dht")
[{#PID<15449.228.0>,
  %{node: :"node2@127.0.0.1", phx_ref: "Pe6xs3WtaDM=", state: :online}},
 {#PID<15551.232.0>,
  %{node: :"node3@127.0.0.1", phx_ref: "PGUKQ2hd0fI=", state: :online}},
 {#PID<0.236.0>,
  %{node: :"node4@127.0.0.1", phx_ref: "m1qD8cn+eMc=", state: :online}},
 {#PID<0.236.0>,
  %{node: :"node4@127.0.0.1", phx_ref: "wDLkDaoxAL8=", state: :online}},
 {#PID<15448.268.0>,
  %{node: :"node1@127.0.0.1", phx_ref: "teoKZJQijs8=", state: :online}}]

```

**Comment by chrismccord** [comment]
Thanks for opening this Gabi. Can you provide the tracker configuration you are using that lets you more easily trigger this? Thanks!

**Comment by gabiz** [comment]
I used the tracker configuration [broadcast_period: 100, max_silent_periods: 3] with 4 nodes.
We pushed voicelayer/dht example to github with those same settings. You can open 4 node instances and restart one a few times to replicate.

One suspect that I have been looking into is `Phoenix.Tracker.State.remove_down_replicas/2`.
I noticed that old replicas are currently not being removed from `State.replicas`, causing this map to grow forever. Keeping the old replicas as `down` in the non-restarting nodes is preventing the old replica Pids from showing up in those nodes. Properly cleaning up `State.replicas` would expose this issue in all nodes.

**Comment by Gazler** [comment]
Here's the output between the error version and the non-error version:

https://gist.github.com/Gazler/1dacae39c4db20a95a25dc8c93545c8a#file-with-ex-L6

**Comment by chrismccord** [comment]
To follow up on irc discussions, it appears the bug is that I failed to reap the permdown'd nodes from the delta generations. As @Gazler's gist shows, the bug happens when we send a delta, but not when we send the entire crdt, and from the code it looks like a simple oversight on my end. I'll dig more later today but it shouldn't be a large fix. Thanks!!
