### ISSUE TITLE
Mismatched pool sizes cause errors/missed messages

### ISSUE THREAD

**Issue by Gazler** [phoenixframework/phoenix_pubsub#59]
When using pubsub with multi-node, if the nodes are configured with different pool sizes, the following situations can occur:

1) `pool_size` is lower than the broadcaster - this results in the error below
2) `pool_size` is greater than the broadcaster - this results in missed messages

The issue stems from forwarding the pool_size based on the broadcaster - https://github.com/phoenixframework/phoenix_pubsub/blob/master/lib/phoenix/pubsub/pg2_server.ex#L36

---

Error:

> 14:41:19.297 [error] Task #PID<0.5811.0> started from Phoenix.PubSub.PubSub terminating
> ** (MatchError) no match of right hand side value: []
>     (phoenix_pubsub) lib/phoenix/pubsub/local.ex:228: Phoenix.PubSub.Local.pools_for_shard/2
>     (phoenix_pubsub) lib/phoenix/pubsub/local.ex:223: Phoenix.PubSub.Local.local_for_shard/2
>     (phoenix_pubsub) lib/phoenix/pubsub/local.ex:152: Phoenix.PubSub.Local.subscribers_with_fastlanes/3
>     (phoenix_pubsub) lib/phoenix/pubsub/local.ex:112: Phoenix.PubSub.Local.do_broadcast/6
>     (phoenix_pubsub) lib/phoenix/pubsub/local.ex:103: anonymous fn/7 in Phoenix.PubSub.Local.broadcast/6
>     (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
>     (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
>     (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
> Function: #Function<4.20419525/0 in Phoenix.PubSub.Local.broadcast/6>
>     Args: []

**Comment by chrismccord** [comment]
closed via https://github.com/phoenixframework/phoenix_pubsub/commit/643eac295ad68581b2434f50f5f1df35db567922 <3 <3 <3

**Comment by Gazler** [comment]
Tested this on master, works perfectly! <3
