### ISSUE TITLE
Enumerable.MapSet.reduce function not found

### ISSUE THREAD

**Issue by michelson** [phoenixframework/phoenix_pubsub#64]
Hi Guys , I’m using phoenix_pubsub in a project, I’ve pushed to a production app and I’m doing some load testing, sadly I getting a lot of errors , one of these is

```
function Enumerable.MapSet.reduce/3 is undefined or private. Did you mean one of:

      * reduce/3
```

the trace tells that the error is from lib/phoenix/tracker/state.ex:362:

then I've remove the build and re compile all , the same error persist but with different trace:

```
function Enumerable.MapSet.reduce/3 is undefined (module Enumerable.MapSet is not available)
```

I'm using:
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [async-threads:10] [kernel-poll:false]
Elixir 1.3.4

**Comment by josevalim** [comment]
Can you add `{:ok, _} = Code.ensure_loaded(Enumerable.MapSet)` to `def start/2` in your application callback (usually in "lib/my_app.ex") and let us know if the error disappears?

Also please double check you are running in production environment.

This is not a Phoenix bug per se. We have had reports of something similar happening but we could not yet reproduce it.

**Comment by michelson** [comment]
Hello @josevalim , 

thanks for your quick reply, I've tunned some sysctl settings on my machine and this error disappeared among other errors.
Also note that I'm using this plugin with a mix application, not a phoenix application. it seems This kinds of errors are raised when process reaches system limits on file descriptors


I'm trying to implement a long polling application which each request is tracked with _Tracker_ and each req starts a PubSub subscriber, if subscriber got message the response is released to the client. (i'm using task async/yield which blocks requests until got response)
I would like to know if this is the correct way to do it, it will scale well ?


```elixir
  get "/api/process/:key" do
    key2 = key |> String.replace(".json", "")
    Phoenix.Tracker.track(Notify.Tracker, self(), "devices", key2, %{stat: "CONNECTED"})
    proc = self()
    Phoenix.PubSub.subscribe Notify.PubSub, key2

    send_resp(conn, 200, "[]")

    task = Task.Supervisor.async_nolink(NotifyWeb.TaskSupervisor, fn ->
      try do
        check_process(proc)
      catch
        :exit, _ -> {:error}
      end
    end)


    conn = put_resp_header(conn, "content-type", "application/json")

    # await for task to return, will also return exit process
    case Task.yield(task, 60000) do
      [] -> send_resp(conn, 200, "[]")
      {:ok, res3}   -> 
        case res3 do
          {:ok, [actions: str]} -> deliver_actions(key2, conn, 200, str)
          {:ok, _} -> send_resp(conn, 200, "[]")
        end
          
      {:exit, _}    -> send_resp(conn, 200, "[]")
      {:error, _}   -> send_resp(conn, 200, "[]")
      nil           -> send_resp(conn, 200, "[]")
      _             -> send_resp(conn, 200, "[]")

    end

  end

  def deliver_actions(key, conn, status, str) do
    send_resp(conn, status, str)
  end

  # recursive function to respond when got data
  def check_process(proc) do
    :timer.sleep(1000)
    case Process.info(proc)[:messages] do
      [] -> check_process(proc) 
      {:ok, [actions: res]} -> {:ok, [actions: res]}
      val -> check_process(proc)
    end
  end



```

**Comment by josevalim** [comment]
> thanks for your quick reply, I've tunned some sysctl settings on my machine and this error disappeared among other errors.

Good call.

> I would like to know if this is the correct way to do it, it will scale well ?

Using `Process.info(prod)[:messages]` and `:timer.sleep(1000)` are usually a no-no. You want the task process to instead send you a message instead of looking into its inbox at every time interval.

In fact, it seems like you don't need the task at all. You can subscribe directly from the request process and use `receive` to await for the message and use `after` for timeout.

**Comment by michelson** [comment]
Thanks José , I will investigate how can I implement that

best regards

**Comment by michelson** [comment]
> You can subscribe directly from the request process and use receive to await for the message and use after for timeout.


having this `Process.info(self)[:messages]` to read messages, how can I use `receive` to listen for new messages ?

I'm trying this:
```elixir    

Phoenix.PubSub.subscribe Notify.PubSub, key

receive do
  {:ok, [actions: res]} -> deliver_actions(key, conn, res)
  {msg} -> IO.inspect msg
  after
  60_000 -> send_resp(conn, 200, "[d]")
end
```

but I only get the `after` response

**Comment by michelson** [comment]
forget it , It was my mistake on the match handling

thanks

**Comment by josevalim** [comment]
@michelson when in doubt, always add a catch all and see what it looks like:

```elixir
receive do
  whatever -> IO.inspect whatever
end
```

:)
