### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by cjimison** [phoenixframework/phoenix_pubsub#69]
We ran into a case where the process that published to a channel is also a subscriber of that channel.  Is there an easy way to pass along a list of pids that should NOT not receive the message even though they are a subscriber?  It would be pretty easy for us to hack this into phoenix_pubsub but I was just wondering if there was already support such an operation before we pulled out the machete :)

Thanks,

-Chris

**Comment by josevalim** [comment]
The broadcast_from_self function exists for this exact purpose.

**Comment by chrismccord** [comment]
As José said, we already have you covered here from the publisher's side. In the case of needing to filter by a list, that is better served by filtering in each client or setting up separate topics.

**Comment by cjimison** [comment]
You guys rock!!!  Thanks again for the help.
