### ISSUE TITLE
Is a `:one_for_one` restart strategy safe for my supervisor?

### ISSUE THREAD

**Issue by myronmarston** [phoenixframework/phoenix_pubsub#76]
We're using this library in a non-phoenix project and are defining our supervision tree ourselves.  Here's the children I'm defining under a supervisor:

``` elixir
    [
      supervisor(Task.Supervisor, [[name: MyApp.PubSubTracker.TaskSupervisor]]),
      supervisor(Phoenix.PubSub.PG2, [MyApp.PubSub, []]),
      worker(MyApp.PubSubTracker, [[
        pubsub_server: MyApp.PubSub,
        name: MyApp.PubSubTracker,
        task_sup: MyApp.PubSubTracker.TaskSupervisor,
      ]]),
    ]
```

We're trying to figure out what restart strategy to use.  When I'm dealing with GenServers I've written I can generally figure out if `:one_for_one` is safe or if I need to use `:rest_for_one`.  Here I' not sure, because I don't know the details of how the tracker and pubsub processes interact.  Is it safe for them to be restarted individually (allowing us to use `:one_for_one`)?  Or do we need to use `:rest_for_one`?

If possible, it would be nice for this to be in the docs.

Thanks!

**Comment by josevalim** [comment]
It is probably fine to be one_for_one because the pubsub tracker is simply going to crash if it tries to use the pubsub while it is down. Also if the tracker is subscribed to pubsub, it should automatically go down in case it crashes.

**Comment by myronmarston** [comment]
Great, thanks.  We'll do that.
