### ISSUE TITLE
Phoenix.PubSub.PG2.start_link/1 missing?

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [phoenixframework/phoenix_pubsub#91]
I noticed that it's not possible to start `Phoenix.PubSub.PG2`by using
```
children = [
  {Phoenix.PubSub.PG2, [:pubsub_name, []]}
]
...
Supervisor.start_link(children, opts)
```
because it result in in `** (UndefinedFunctionError) function Phoenix.PubSub.PG2Server.start_link/1 is undefined or private.`.

Is this the intended behaviour or am I missing anything?

Thanks!

**Comment by chrismccord** [comment]
The PG2 module expects two arguments. I believe you meant:

```elixir
{Phoenix.PubSub.PG2, [[:pubsub_name, []]]}
```
