### ISSUE TITLE
no function clause matching in Phoenix.PubSub.subscribe/2

### ISSUE THREAD

**Issue by rmoorman** [phoenixframework/phoenix_pubsub#92]
Hello,

I just noticed that while you can use `Phoenix.PubSub.subscribe/2` to subscribe to presence changes, you may only do so when your topic is of binary type.
On the other hand, one can track presence with arbitrary things as topic and presence listing does work fine (haven't tested multi-node setup)

So this does work:
~~~
iex(dingen@localhost)15> Phoenix.PubSub.subscribe(Dingen.PubSub, "dingen:12345")
:ok


iex(dingen@localhost)7> DingenWeb.Presence.track(self(), "dingen:12345", "dingen", %{})
{:ok, "SMcm2taTxLw="}


iex(dingen@localhost)17> flush
%Phoenix.Socket.Broadcast{event: "presence_diff",
 payload: %{joins: %{"dingen" => %{metas: [%{phx_ref: "SMcm2taTxLw="}]}},
   leaves: %{}}, topic: "dingen:12345"}
:ok
~~~

While this doesn't
~~~
iex(dingen@localhost)15> Phoenix.PubSub.subscribe(Dingen.PubSub, {"game", 12345})
** (FunctionClauseError) no function clause matching in Phoenix.PubSub.subscribe/2

    The following arguments were given to Phoenix.PubSub.subscribe/2:

        # 1
        Dingen.PubSub

        # 2
        {"game", 12345}

    Attempted function clauses (showing 1 out of 1):

        def subscribe(server, topic) when is_atom(server) and -is_binary(topic)-

    (phoenix_pubsub) lib/phoenix/pubsub.ex:151: Phoenix.PubSub.subscribe/2


iex(dingen@localhost)4> DingenWeb.Presence.track(self(), {"game", 12345}, "dingen", %{})
{:ok, "RY19Y4RqB8Q="}
~~~

On IRC I heard that I should not count on the behaviour of Presence track allowing for arbitrary topic names so maybe some guard clause is missing. Or maybe the other way around that Presence does support it by design and maybe PubSub should too?

Anyway, I thought I'd rather report it.

Best regards

**Comment by chrismccord** [comment]
You are right that we only support string topics. Thanks for the report!

**Comment by josevalim** [comment]
We still support only string topics but we use the registry now, so it should be easy to change if we want to in the future.
