### ISSUE TITLE
Potential problem with documentation

### ISSUE THREAD

**Issue by SLsthompson** [phoenixframework/phoenix_pubsub#99]
In the documentation (https://hexdocs.pm/phoenix_pubsub/Phoenix.Tracker.html) under the heading "Implementing a Tracker" where it does:

    defmodule MyTracker do
      @behavior Phoenix.Tracker
      ...

It then goes on to define a `start_link` that calls `GenServer.start_link`

Should that sample code not include `use GenServer` as well?  Without it, the module does not define `child_spec` and, like #94, problems with the deprecation of `Supervisor.Spec` ensue.

(if the change is appropriate, I would be happy to put together a pull request to make it)

**Comment by chrismccord** [comment]
Please send a PR to include child_spec in the example under that heading. Thanks!

**Comment by josevalim** [comment]
Fixed, thanks!
